spring:
  application:
    name: Transaction routine API

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

